import Foundation

/// Wrong answers for the multiple-choice warmup mode.
///
/// Picked locally rather than generated by a model: same-part-of-speech words
/// drawn from the catalog are plausible enough for a warmup, and cost nothing.
public enum DistractorPicker {

    /// Wrong definitions for the multiple-choice mode.
    ///
    /// The word ships its own: hand-written near misses in the same register,
    /// wrong on the one point that matters. Borrowing three other words'
    /// definitions makes the question answerable without knowing the word,
    /// since the odd one out is the only definition that fits the prompt at all.
    public static func definitionDistractors(
        for word: Word, from catalog: WordCatalog, count: Int = 3
    ) -> [String] {
        let written = word.gre?.distractors ?? []
        if written.count >= count { return Array(written.prefix(count)) }
        let filler = pick(count - written.count,
                          from: catalog.words(withPartOfSpeech: word.primaryPartOfSpeech)
                              .filter { $0.id != word.id },
                          seed: stableHash("definition-" + word.id))
        return written + filler.map(\.teachingDefinition)
    }

    /// Wrong words for a fill-in-the-blank.
    ///
    /// Same part of speech *and* a similar difficulty, so the answer cannot be
    /// found by spotting the one word the learner recognises. Widens the band
    /// rather than returning short if the narrow pool is too small.
    public static func clozeDistractors(
        for word: Word, from catalog: WordCatalog, count: Int = 3
    ) -> [Word] {
        let sameKind = catalog.words(withPartOfSpeech: word.primaryPartOfSpeech)
            .filter { $0.id != word.id }
        for tolerance in 0...4 {
            let pool = sameKind.filter { abs($0.rating - word.rating) <= tolerance }
            if pool.count >= count {
                return pick(count, from: pool, seed: stableHash("cloze-" + word.id))
            }
        }
        return pick(count, from: sameKind, seed: stableHash("cloze-" + word.id))
    }

    /// Wrong meanings for "which sense is used here?".
    ///
    /// Drawn from the word's *own* other WordNet senses, which is what makes
    /// the question worth asking: the distractors are the everyday meanings the
    /// learner already knows and the exam is counting on them to choose.
    public static func senseDistractors(
        for word: Word, from catalog: WordCatalog, count: Int = 3
    ) -> [String] {
        let tested = word.teachingDefinition.lowercased()
        var options = word.senses
            .map(\.definition)
            .filter { $0.lowercased() != tested }

        // A trap with only one WordNet sense borrows definitions from unrelated
        // words rather than dropping to a two-option question.
        if options.count < count {
            let filler = pick(count - options.count,
                              from: catalog.words.filter { $0.id != word.id },
                              seed: stableHash("sense-" + word.id))
            options += filler.map(\.teachingDefinition)
        }
        return Array(options.prefix(count))
    }

    private static func pick(
        _ count: Int, from pool: [Word], seed: UInt64
    ) -> [Word] {
        guard !pool.isEmpty else { return [] }

        // Deterministic per word, so the same question always offers the same
        // options -- a learner who sees a question twice should not be able to
        // tell the answer apart by the company it keeps.
        var rng = SeededGenerator(seed: seed)
        var picked: [Word] = []
        var seen = Set<String>()
        var attempts = 0
        let limit = count * 20

        while picked.count < count && attempts < limit {
            attempts += 1
            let candidate = pool[Int(rng.next() % UInt64(pool.count))]
            if seen.insert(candidate.id).inserted { picked.append(candidate) }
        }
        return picked
    }
}

/// xorshift64*, seeded explicitly so results survive a relaunch.
struct SeededGenerator: RandomNumberGenerator {
    private var state: UInt64

    init(seed: UInt64) { state = seed == 0 ? 0x9E3779B97F4A7C15 : seed }

    mutating func next() -> UInt64 {
        state ^= state >> 12
        state ^= state << 25
        state ^= state >> 27
        return state &* 2_685_821_657_736_338_717
    }
}
