import Foundation

/// Wrong answers for the multiple-choice warmup mode.
///
/// Picked locally rather than generated by a model: same-part-of-speech words
/// drawn from the catalog are plausible enough for a warmup, and cost nothing.
public enum DistractorPicker {

    public static func distractors(
        for word: Word, from catalog: WordCatalog, count: Int = 3
    ) -> [Word] {
        let pool = catalog.words(withPartOfSpeech: word.primaryPartOfSpeech)
            .filter { $0.id != word.id }
        guard !pool.isEmpty else { return [] }

        // Deterministic per word, so the same question always offers the same
        // options -- a learner who sees a question twice should not be able to
        // tell the answer apart by the company it keeps.
        var rng = SeededGenerator(seed: stableHash(word.id))
        var picked: [Word] = []
        var seen = Set<String>()
        var attempts = 0
        let limit = count * 20

        while picked.count < count && attempts < limit {
            attempts += 1
            let candidate = pool[Int(rng.next() % UInt64(pool.count))]
            if seen.insert(candidate.id).inserted { picked.append(candidate) }
        }
        return picked
    }
}

/// xorshift64*, seeded explicitly so results survive a relaunch.
struct SeededGenerator: RandomNumberGenerator {
    private var state: UInt64

    init(seed: UInt64) { state = seed == 0 ? 0x9E3779B97F4A7C15 : seed }

    mutating func next() -> UInt64 {
        state ^= state >> 12
        state ^= state << 25
        state ^= state >> 27
        return state &* 2_685_821_657_736_338_717
    }
}
